config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/' do 
  	scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do 
  		resources :comments
  		resources :shelters
  	end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	 validates_presence_of :author, :comment
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/shelter.rb
class Shelter < ApplicationRecord
	validates_presence_of :name, :address, :phone, :beds
	has_one :location
	geocoded_by :address
	after_validation :geocode
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController

  def index
    @comments = Comment.all.order(:id).reverse
    respond_with @comments
  end

  def show
    @comment = Comment.find(params[:id])
    respond_with @comment
  end

  def create
    params.inspect
    @comment = Comment.new(comment_params)
    if @comment.save
      render json: @comment, status: 201
    else
      render json: { errors: @comment.errors.full_messages }, status: 422
    end
  end


  private

    def comment_params
      params.require(:comment).permit(:author, :comment)
    end

end

app/controllers/api/v1/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  def index
    @locations = Location.all
  end

  # GET /locations/1
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to @location, notice: 'Location was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      redirect_to @location, notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy
    redirect_to locations_url, notice: 'Location was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/controllers/api/v1/shelters_controller.rb
class Api::V1::SheltersController < ApplicationController

  def index
    @shelters = Shelter.all.order(:id).reverse
    respond_with @shelters
  end

  def show
    @shelter = Shelter.find(params[:id])
    respond_with @shelter
  end

  def create
    print "these are the shelter params" 
    print :shelter
    @shelter = Shelter.new(shelter_params)
    # if @shelter.save
    #   render json: @shelter, status: 201
    # else
    #   render json: { errors: @shelter.errors.full_messages }, status: 422
    # end
  end


  private

    def shelter_params
      params.require(:shelter).permit(:name, :address, :phone, :beds)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
	
	respond_to :json

	before_action :ensure_json_request  

	def ensure_json_request  
	  return if request.format == :json
	  render :nothing => true, :status => 406  
	end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(location) do |f| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>